### ISSUE TITLE
Set up a Wikimedia cloak

### ISSUE THREAD

**Issue by Genesis2rise** [countervandalism/infrastructure#14]
Hi there ! Please set up a wikimedia cloak for my irc account.

1. https://meta.wikimedia.org/wiki/User:Tulsi_Bhagat
2. https://mai.wikipedia.org/wiki/Special:diff/159651
3. Cloak: wikimedia/Tulsi_Bhagat
4. E-mail: tulsibhagat50@gmail.com
5. Nick: Tulsi

Thanks,
Tulsi

**Comment by rxywm** [comment]
Out of CVN project scope.
Please read [this](https://meta.wikimedia.org/wiki/IRC/Cloaks#Obtaining_a_cloak) document for requesting Wikimedia Cloak.
