### ISSUE TITLE
SWBot3 (#cvn-simplewikis); change reports of account creation

### ISSUE THREAD

**Issue by Vermontwiki** [countervandalism/infrastructure#18]
Currently, the bot includes a link to block the account when a new account is made. It would be much more beneficial to include a link to the contributions page, or central auth. Most people who patrol in the channel are not Administrators (only 1 is), thus the link to block the user is useless as there is no quick way to get from there to the user’s contributions.

**Comment by rxywm** [comment]
✔️ done
