### ISSUE TITLE
Create a CVN bot for #cvn-es-scan

### ISSUE THREAD

**Issue by Wiki1776** [countervandalism/infrastructure#21]
I request the creation of a bot to patrol all wikis in Spanish, except es.wikipedia.

The wikis are:
1) eswikivoyage (es.wikivoyage.org)
2) eswikinews ( es.wikinews.org)
3) eswikiquote (es.wikiquote.org)
4) eswikisource ( es.wikisource.org)
5) eswikibooks (es.wikibooks.org)
6) eswiktionary (es.wiktionary.org)
7) eswikiversity (es.wikiversity.org)

The bot should report all edits and actions you performed.

**Comment by ucronistaw** [comment]
@Krinkle Thanks!
