### ISSUE TITLE
Bots failing to pull RC feeds

### ISSUE THREAD

**Issue by Cameron11598** [countervandalism/infrastructure#22]
IRC Log attached with restart times after being told the bots weren't pulling RC feeds. 

- ____TIMES ARE UTC-8___
- [2018-11-08 17:45:21] <Thanksgiving> Cvnbot3 restart
- [2018-11-09 15:48:27] <Thanksgiving> CVNBot18 restart
- [2018-11-09 15:48:38] <Thanksgiving> CVNBot2 restart
- [2018-11-09 15:50:21] <Thanksgiving> cvnbot12 restart
- [2018-11-09 15:51:29] <Thanksgiving> cvnbot19 status
- [2018-11-09 15:52:00] <Thanksgiving> cvnbot21 restart
- [2018-11-09 15:52:06] <Thanksgiving> cvnbot22 restart
- [2018-11-09 15:52:35] <Thanksgiving> cvnbot27 status
- [2018-11-09 19:40:50] <Krinkle> CVNBot4 restart
- [2018-11-09 19:40:53] <Krinkle> CVNBot5 restart
- [2018-11-09 19:41:17] <Krinkle> SWBot3 restart
- [2018-11-11 15:58:50] <Thanksgiving> Cvnbot3 restart
- [2018-11-11 15:59:05] <Thanksgiving> Cvnbot18 restart
- [2018-11-14 17:00:53] <rxy> CVNBot6 restart
- [2018-11-14 17:00:54] <rxy> CVNBot7 restart
- [2018-11-14 17:00:56] <rxy> CVNBot8 restart
- [2018-11-14 17:00:58] <rxy> CVNBot9 restart
- [2018-11-18 02:20:03] <rxy> CVNBot1 restart
- [2018-11-18 02:20:05] <rxy> CVNBot2 restart
- [2018-11-18 02:20:08] <rxy> CVNBot3 restart
- [2018-11-18 02:20:09] <rxy> CVNBot4 restart
- [2018-11-18 02:20:14] <rxy> CVNBot6 restart
- [2018-11-18 02:20:19] <rxy> CVNBot8 restart
- [2018-11-18 02:20:20] <rxy> CVNBot9 restart
- [2018-11-18 02:20:25] <rxy> CVNBot11 restart
- [2018-11-18 02:20:27] <rxy> CVNBot12 restart
- [2018-11-18 02:20:23] <rxy> CVNBot10 restart
- [2018-11-18 02:20:25] <rxy> CVNBot11 restart
- [2018-11-18 02:20:27] <rxy> CVNBot12 restart
- [2018-11-18 02:20:32] <rxy> CVNBot16 restart
- [2018-11-18 02:20:34] <rxy> CVNBot17 restart
- [2018-11-18 02:20:36] <rxy> CVNBot18 restart
- [2018-11-18 02:20:38] <rxy> CVNBot19 restart
- [2018-11-18 02:20:40] <rxy> CVNBot20 restart
- [2018-11-18 02:20:42] <rxy> CVNBot21 restart
- [2018-11-18 02:20:44] <rxy> CVNBot22 restart
- [2018-11-18 02:20:46] <rxy> CVNBot23 restart (several other bots restarted)
- [2018-11-21 07:54:33] <rxy> CVNBot3 restart
- [2018-11-22 09:20:41] <rxy> CVNBot6 restart
- [2018-11-22 09:20:54] <rxy> CVNBot restart
- [2018-11-22 09:20:54] <rxy> CVNBot7 restart
- [2018-11-22 09:31:26] <rxy> CVNBot27 restart
- [2018-11-27 01:59:18] <AlexZ_> CVNBot6 restart
- [2018-11-27 01:59:24] <AlexZ_> CVNBot7 restart
- [2018-11-27 01:59:28] <AlexZ_> CVNBot8 restart
- [2018-11-27 01:59:32] <AlexZ_> CVNBot9 restart
- [2018-11-27 01:59:36] <AlexZ_> CVNBot19 restart
- [2018-11-29 12:42:23] <Cam11598> CVNBot6 restart
- [2018-11-29 12:42:55] <Cam11598> CVNBot8 restart
- [2018-11-29 16:23:07] <Cam11598> CVNBot1 restart
- ____TIMES ARE UTC___
- [2018-11-26 16:07] SWBot3 Restarted

**Comment by Cameron11598** [comment]
Log of restarts from IRC Cloud attached

[CVNBOT RESTARTS.txt](https://github.com/countervandalism/infrastructure/files/2631453/CVNBOT.RESTARTS.txt)

**Comment by Cameron11598** [comment]
Times are UTC-8 
2:22:40 PM <@rxy> CVNBot18 restart
2:22:41 PM ← +CVNBot18 left (~CVNBot18@cvn/bot/cvn-bots4): "Rebooting by order of rxy ..."
2:22:57 PM <@rxy> CVNBot3 restart
2:22:57 PM → +CVNBot18 (voiced) joined  ↔ +CVNBot3 (voiced), +CVNBot16 (voiced) and +CVNBot7 (voiced) nipped out

**Comment by Cameron11598** [comment]
None of these bots appeared to be in their irc.wikimedia channels. 


See Log: https://wikitech.wikimedia.org/w/index.php?title=Nova_Resource%3ACvn%2FSAL&type=revision&diff=1810001&oldid=1809993

**Comment by Cameron11598** [comment]
___TIMES ARE UTC-8_____
11:59:49 AM <@Cam11598> CVNBot18 status
11:59:49 AM <+CVNBot18> Last message was received on RCReader 118066.396796 seconds ago
11:59:55 AM <@Cam11598> CVNBot18 restart
11:59:56 AM ← +CVNBot18 left (~CVNBot18@cvn/bot/cvn-bots4): "Rebooting by order of Cam11598 
12:00:00 PM <@Cam11598> Cubbie status
12:00:00 PM <+Cubbie> Last message was received on RCReader 191898.12268 seconds ago
12:00:11 PM <@Cam11598> Cubbie restart
12:00:12 PM ← +Cubbie left (~Cubbie@cvn/bot/cvn-bots4): "Rebooting by order of Cam11598 ..."
12:00:26 PM → Cubbie joined (~Cubbie@185.15.56.21)
12:00:30 PM ⇐ Cubbie quit (~Cubbie@185.15.56.21) Changing host
12:00:30 PM → Cubbie joined (~Cubbie@cvn/bot/cvn-bots4)

**Comment by Cameron11598** [comment]
Times are UTC-8

12:03:46 PM <@Cam11598> cvnbot3 status
12:03:46 PM <+CVNBot3> Last message was received on RCReader 192160.850344 seconds ago
12:03:52 PM <@Cam11598> cvnbot3 restart
12:03:52 PM ↔ +CVNBot3 (voiced) nipped out  
12:03:52 PM ← +CVNBot3 left (~CVNBot3@cvn/bot/cvn-bots): "Rebooting by order of Cam11598 ..."
12:04:06 PM → CVNBot3 joined (~CVNBot3@cvn/bot/cvn-bots)
12:04:06 PM +CVNBot3 was voiced (+v) by @ChanServ

**Comment by Cameron11598** [comment]
[2018-12-06 06:42:26] ⇐ Cubbie quit (~CVNBot@anonymous.user): Remote host closed the connection

**Comment by Krinkle** [comment]
https://tools.wmflabs.org/nagf/?project=cvn&range=year#h_cvn-app9_memory

<img width="858" alt="cvn-app8 memory usage over 12 months" src="https://user-images.githubusercontent.com/156867/50551355-0c8e5d00-0c34-11e9-85f6-70da12dbc568.png">
<img width="853" alt="cvn-app8 memory usage over 12 months" src="https://user-images.githubusercontent.com/156867/50551356-0c8e5d00-0c34-11e9-87b3-b55d28182ef8.png">

**Comment by Krinkle** [comment]
Ref https://github.com/countervandalism/CVNBot/issues/13
