### ISSUE TITLE
Create a CVN bot for #cvn-bn-scan

### ISSUE THREAD

**Issue by tanvirglhs** [countervandalism/infrastructure#5]
Please create a CVN bot for #cvn-bn-scan to patrol all Bangla wikis. Currently there are four Bangla (bn) Wikimedia conent wikis. They are the following.

1. bnwiki (bn.wikipedia.org)
2. bnwikibooks (bn.wikibooks.org)
3. bnwikisource (bn.wikisource.org)
4. bnwiktionary (bn.wiktionary.org)

In addition, (if at all possible) it should also patrol all edits on bd.wikimedia.org (the Chapter wiki of Wikimedia Bangladesh).

We don't have a lot of edits at the moment. Therefore the bot should report every edits, moves, and actions by all editors except flagged bots and those who have flood flags.

The channel #cvn-bn-scan is already configured by a CVN staff according to the CVN policy.

Thank you.

**Comment by rxywm** [comment]
:white_check_mark:  Created in  7 Aug 2015 (countervandalism/stillalive@ff71954900e079eb687aa4a29f407a5ffdf789d8)
