### ISSUE TITLE
Create a CNV bot for #cvn-sw-mk

### ISSUE THREAD

**Issue by m4r51n** [countervandalism/infrastructure#6]
Please create a CVN bot for #cvn-sw-mk to patrol all Macedonian wikis. 

mkwiki (mk.wikipedia.org)
mkwikibooks (mk.wikibooks.org)

We don't have a lot of edits at the moment. Therefore the bot should report every edits, moves, and actions by all editors except flagged bots and those who have flood flags.

Thank you.

**Comment by rxywm** [comment]
:white_check_mark:  done. Channel name is #cvn-mk-scan for standardisation (like a #cvn-it-scan , #cvn-zh-scan).
